---
# Recursor + forwarders
bind9_recursor: true
bind9_forward: true
bind9_forward_servers:
  - "1.1.1.1"
  - "9.9.9.9"

# Exécution en root dans ce lab: évite les erreurs de droits sur les volumes host (/srv/bind9/*)
bind9_docker_user: "root"
bind9_docker_dir_mode: "0755"
bind9_docker_file_mode: "0644"

# Réseaux autorisés à résoudre via ce DNS
bind9_our_networks:
  - "172.16.100.0/24"
  - "10.20.71.0/24"
  - localhost

# Zone interne 
bind9_authoritative: true
bind9_zones_dynamic:
  - name: "jdk.lab"
    type: master
    serial: 2026011701
    admin: "postmaster.jdk.lab"
    ns_records:
      - "ns1.jdk.lab"
    rrs:
      - { label: "ns1", type: "A", rdata: "172.16.100.254" }
      - { label: "ubuntu-host", type: "A", rdata: "172.16.100.100" }
  - name: "lab.local"
    type: master
    serial: 2026021703
    admin: "postmaster.lab.local"
    ns_records:
      - "dns-server.lab.local"
    rrs:
      - { label: "dns-server", type: "A", rdata: "172.16.100.254" }
      - { label: "harbor", type: "A", rdata: "172.16.100.253" }
      - { label: "portainer", type: "A", rdata: "172.16.100.253" }
      - { label: "git-lab", type: "A", rdata: "172.16.100.253" }
      - { label: "gitlab", type: "CNAME", rdata: "git-lab.lab.local." }
      - { label: "registry", type: "A", rdata: "172.16.100.253" }
      - { label: "registry.gitlab", type: "A", rdata: "172.16.100.253" }
      - { label: "taiga", type: "A", rdata: "172.16.100.253" }
      - { label: "edgedoc", type: "A", rdata: "172.16.100.253" }
      - { label: "grafana", type: "A", rdata: "172.16.100.253" }
      - { label: "prometheus", type: "A", rdata: "172.16.100.253" }
      - { label: "alertmanager", type: "A", rdata: "172.16.100.253" }
      - { label: "bind9dns", type: "A", rdata: "172.16.100.254" }
      - { label: "reverse-proxy", type: "A", rdata: "172.16.100.253" }
      - { label: "tools-manager", type: "A", rdata: "172.16.100.20" }
      - { label: "harbor-vm", type: "A", rdata: "172.16.100.50" }
      - { label: "git-lab-vm", type: "A", rdata: "172.16.100.40" }
      - { label: "monitoring-stack", type: "A", rdata: "172.16.100.60" }
      - { label: "k3s-manager", type: "A", rdata: "172.16.100.250" }
      - { label: "k3s-worker-0", type: "A", rdata: "172.16.100.251" }
      - { label: "k3s-worker-1", type: "A", rdata: "172.16.100.252" }
