---
- name: Déploiement Stack Monitoring
  hosts: monitoring_hosts
  become: true

  roles:
    - role: monitoring

- name: Installation Node Exporter (toutes VMs)
  hosts: all
  become: true

  roles:
    - role: node_exporter
      tags: ["node_exporter"]
